spring:
  application:
    name: fundiconnect-api
  datasource:
    url: jdbc:postgresql://localhost:5432/fundiconnect
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8080